import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { GlobalNavBar } from "@/components/molecules/nav-bar";
import { TanstackProvider } from "@/client/providers/tanstack-provider";
import { ApolloProviderWrapper } from "@/client/providers/apollo-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

// export const metadata: Metadata = {
//   title: "Sri Maruthi Traders",
//   description: "Generated by create next app",
// };
const APP_NAME = "Mandi App";
const APP_DEFAULT_TITLE = "Mandi Management System";
const APP_TITLE_TEMPLATE = "%s - App";
const APP_DESCRIPTION = "Your Complete Mandi Management System";
export const metadata: Metadata = {
  applicationName: APP_NAME,
  icons: {
    icon: "/assets/hanuman.png",
  },
  title: {
    default: APP_DEFAULT_TITLE,
    template: APP_TITLE_TEMPLATE,
  },
  description: APP_DESCRIPTION,
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: APP_DEFAULT_TITLE,
    // startUpImage: [],
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: "website",
    siteName: APP_NAME,
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
  twitter: {
    card: "summary",
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "mt-[85px]")}>
        <ApolloProviderWrapper>
          <TanstackProvider>
            <GlobalNavBar />
            {children}
          </TanstackProvider>
        </ApolloProviderWrapper>
      </body>
    </html>
  );
}
