import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { GlobalNavBar } from "@/components/molecules/nav-bar";
import { TanstackProvider } from "@/client/providers/tanstack-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Sri Maruthi Traders",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <TanstackProvider>
          <GlobalNavBar />
          {children}
        </TanstackProvider>
      </body>
    </html>
  );
}
